---
- name: Install the required packages in Debian derivatives
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ network_pkgs }}"
  environment: "{{ env }}"
  when: network_check_packages

- name: Make sure the include line is there in interfaces file
  lineinfile:
    regexp: '^source\ {{ net_path | regex_escape() }}/\*'
    line: "source {{ net_path }}/*"
    dest: /etc/network/interfaces
    state: present
    insertafter: EOF

- name: Create the directory for interface cfg files
  file:
    path: "{{ net_path }}"
    state: directory
